steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/gcp-ml-dive/product-classifier:latest", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/gcp-ml-dive/product-classifier:latest"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
        "run",
        "deploy",
        "product-classifier",
        "--image=gcr.io/gcp-ml-dive/product-classifier:latest",
        "--region=northamerica-northeast2",
        "--allow-unauthenticated", # authentication handled on the backend
        "--memory=4Gi"
      ]
# Optional images configuration to specify global image substitution variables
images:
  - "gcr.io/gcp-ml-dive/product-classifier:latest"